#!/bin/bash
DIRECTORY=$(dirname "$0")
echo "Changing to ${DIRECTORY}"
cd  "$DIRECTORY" || exit 1

echo "Run your project here."

domains=()
challenge_type=$1
shift
while [ $# -gt 0 ]; do
     key="$1"
     case $key in
          --revoke)
          revoked=revoke
          ;;
          --dir)
          dir="$2"
          ;;
          --record)
          record="$2"
          ;;
          --domain)
          domains+="$2 "
          ;;
          *) break
          ;;
     esac
     shift
     shift
done
python3 dnsserver.py $record & 
python3 main.py $challenge_type $dir $record $domains $revoked