#!/bin/bash
DIRECTORY=$(dirname "$0")
echo "Changing to ${DIRECTORY}"
cd  "$DIRECTORY" || exit 1

echo "Run your project here."

domains=()
challenge_type=$1
shift
while [ $# -gt 0 ]; do
     key="$1"
     case $key in
          --dir)
          dir="$2"
          shift
          shift
          ;;
          --record)
          record="$2"
          shift
          shift
          ;;
          --domain)
          domains+="$2"
          shift
          shift
          ;;
          *)
          ;;
     esac
done

python3 main.py $challenge_type $dir $record $domains